In [66]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [67]:
df = pd.read_csv(r'C:\Users\Kato\Version3.12\bank-marketing-analysis\data\bank-full.csv', sep=';')
df.head(5)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [68]:
df['y'].value_counts()

y
no     39922
yes     5289
Name: count, dtype: int64

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  str
 2   marital    45211 non-null  str
 3   education  45211 non-null  str
 4   default    45211 non-null  str
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  str
 7   loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   day        45211 non-null  int64
 10  month      45211 non-null  str
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  y          45211 non-null  str
dtypes: int64(7), str(10)
memory usage: 5.9 MB

In [70]:
df.shape

(45211, 17)

In [71]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='str')

In [72]:
df.dtypes

age          int64
job            str
marital        str
education      str
default        str
balance      int64
housing        str
loan           str
contact        str
day          int64
month          str
duration     int64
campaign     int64
pdays        int64
previous     int64
poutcome       str
y              str
dtype: object

In [73]:
numerical_cols = ['age', 'balance', 'campaign', 'previous', 'day', 'was_previously_contacted', 'days_since_prev_contact', 'month_sin', 'month_cos']
nominal_categorical = ['job', 'marital', 'default', 'housing', 'loan', 'contact', 'poutcome', 'education']
#calendar = ['month'] converted to month_sin and month_cos
#special = ['pdays'] performed feature engineering on this
categorical_cols = [k for k in df.columns if k not in numerical_cols and k != 'y']

In [74]:
for col in df.columns:
    print(f'--- {col} ---')
    print(df[col].nunique())
    print('----------------')
    print(df[col].value_counts().head(5))

--- age ---
77
----------------
age
32    2085
31    1996
33    1972
34    1930
35    1894
Name: count, dtype: int64
--- job ---
12
----------------
job
blue-collar    9732
management     9458
technician     7597
admin.         5171
services       4154
Name: count, dtype: int64
--- marital ---
3
----------------
marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64
--- education ---
4
----------------
education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64
--- default ---
2
----------------
default
no     44396
yes      815
Name: count, dtype: int64
--- balance ---
7168
----------------
balance
0    3514
1     195
2     156
4     139
3     134
Name: count, dtype: int64
--- housing ---
2
----------------
housing
yes    25130
no     20081
Name: count, dtype: int64
--- loan ---
2
----------------
loan
no     37967
yes     7244
Name: count, dtype: int64
--- contact ---
3
----------------
contact
cellular     29285
unknown      13020
telephone     2906
Name: count, dtype: int64
--- day ---
31
----------------
day
20    2752
18    2308
21    2026
17    1939
6     1932
Name: count, dtype: int64
--- month ---
12
----------------
month
may    13766
jul     6895
aug     6247
jun     5341
nov     3970
Name: count, dtype: int64
--- duration ---
1573
----------------
duration
124    188
90     184
89     177
104    175
114    175
Name: count, dtype: int64
--- campaign ---
48
----------------
campaign
1    17544
2    12505
3     5521
4     3522
5     1764
Name: count, dtype: int64
--- pdays ---
559
----------------
pdays
-1      36954
 182      167
 92       147
 91       126
 183      126
Name: count, dtype: int64
--- previous ---
41
----------------
previous
0    36954
1     2772
2     2106
3     1142
4      714
Name: count, dtype: int64
--- poutcome ---
4
----------------
poutcome
unknown    36959
failure     4901
other       1840
success     1511
Name: count, dtype: int64
--- y ---
2
----------------
y
no     39922
yes     5289
Name: count, dtype: int64

In [75]:
print(df['day'].describe())

count    45211.000000
mean        15.806419
std          8.322476
min          1.000000
25%          8.000000
50%         16.000000
75%         21.000000
max         31.000000
Name: day, dtype: float64

In [76]:
df['was_previously_contacted'] = (df['pdays'] != -1).astype(int)
df['days_since_prev_contact'] = df['pdays'].replace(-1, np.nan)
df.drop('pdays', axis=1, inplace=True)
df.tail(5)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,previous,poutcome,y,was_previously_contacted,days_since_prev_contact
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,0,unknown,yes,0,NaN
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,0,unknown,yes,0,NaN
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,3,success,yes,1,184.0
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,0,unknown,no,0,NaN
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,11,other,no,1,188.0

In [122]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, classification_report

In [105]:
month_map = {
    'jan':1,
    'feb':2,
    'mar':3,
    'apr':4,
    'may':5,
    'jun':6,
    'jul':7,
    'aug':8,
    'sep':9,
    'oct':10,
    'nov':11,
    'dec':12
}
df['month_num'] = df['month'].map(month_map)
df['month_num'].value_counts()

month_num
5     13766
7      6895
8      6247
6      5341
11     3970
4      2932
2      2649
1      1403
10      738
9       579
3       477
12      214
Name: count, dtype: int64

In [106]:
df['month_sin'] = np.sin((2 * np.pi * (df['month_num'] / 12)))
df['month_cos'] = np.cos((2 * np.pi * (df['month_num'] / 12)))
df.drop('month_num', axis=1, inplace=True)

In [107]:
df['days_since_prev_contact'] = df['days_since_prev_contact'].replace(np.nan, 0)

In [108]:
x = df.drop('y', axis = 1)
y = df['y']

In [109]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=42)

In [110]:
ct = ColumnTransformer([
    ('numerical', StandardScaler(), numerical_cols),
    ('categorical', OneHotEncoder(handle_unknown='ignore'), nominal_categorical)
])

In [111]:
ct.fit(x_train)

ColumnTransformer(transformers=[('numerical', StandardScaler(),
                                 ['age', 'balance', 'campaign', 'previous',
                                  'day', 'was_previously_contacted',
                                  'days_since_prev_contact', 'month_sin',
                                  'month_cos']),
                                ('categorical',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['job', 'marital', 'default', 'housing',
                                  'loan', 'contact', 'poutcome',
                                  'education'])])

In [112]:
x_train_transformed = ct.transform(x_train)
x_test_transformed = ct.transform(x_test)

In [113]:
ct.get_feature_names_out()

array(['numerical__age', 'numerical__balance', 'numerical__campaign',
       'numerical__previous', 'numerical__day',
       'numerical__was_previously_contacted',
       'numerical__days_since_prev_contact', 'numerical__month_sin',
       'numerical__month_cos', 'categorical__job_admin.',
       'categorical__job_blue-collar', 'categorical__job_entrepreneur',
       'categorical__job_housemaid', 'categorical__job_management',
       'categorical__job_retired', 'categorical__job_self-employed',
       'categorical__job_services', 'categorical__job_student',
       'categorical__job_technician', 'categorical__job_unemployed',
       'categorical__job_unknown', 'categorical__marital_divorced',
       'categorical__marital_married', 'categorical__marital_single',
       'categorical__default_no', 'categorical__default_yes',
       'categorical__housing_no', 'categorical__housing_yes',
       'categorical__loan_no', 'categorical__loan_yes',
       'categorical__contact_cellular', 'categorical__contact_telephone',
       'categorical__contact_unknown', 'categorical__poutcome_failure',
       'categorical__poutcome_other', 'categorical__poutcome_success',
       'categorical__poutcome_unknown', 'categorical__education_primary',
       'categorical__education_secondary',
       'categorical__education_tertiary',
       'categorical__education_unknown'], dtype=object)

In [189]:
_n = 11
knn = KNeighborsClassifier(n_neighbors=_n)
knn.fit(x_train_transformed, y_train)

KNeighborsClassifier(n_neighbors=11)

In [190]:
y_pred = knn.predict(x_test_transformed)
y_pred[:20]

array(['no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no'], dtype=object)

In [191]:
y_test.iloc[:20].values

<StringArray>
[ 'no',  'no',  'no',  'no',  'no',  'no',  'no', 'yes',  'no',  'no',  'no',
  'no',  'no',  'no',  'no',  'no',  'no',  'no', 'yes',  'no']
Length: 20, dtype: str

In [192]:
m = confusion_matrix(y_test, y_pred)
data = f"""------------------- n_neighbors: {_n} --------------------\n
Accuracy: {accuracy_score(y_test, y_pred)}\n
Confusion Matrix: [{m[0, 0]}, {m[0, 1]}]
                  [{m[1, 0]}, {m[1, 1]}]\n
Classification Report:\n
{classification_report(y_test, y_pred)}
"""
print(data)

------------------- n_neighbors: 11 --------------------

Accuracy: 0.8894172287957536

Confusion Matrix: [7857, 128]
                  [872, 186]

Classification Report:

              precision    recall  f1-score   support

          no       0.90      0.98      0.94      7985
         yes       0.59      0.18      0.27      1058

    accuracy                           0.89      9043
   macro avg       0.75      0.58      0.61      9043
weighted avg       0.86      0.89      0.86      9043

In [193]:
with open('knn_classifier_manual_optimization.txt', 'a', encoding='utf-8') as kco:
    kco.write(data)

In [217]:
#trying to construct a pipeline

#from sklearn.pipeline import Pipeline
from sklearn.metrics import f1_score, make_scorer
from sklearn.model_selection import GridSearchCV
from imblearn.over_sampling import RandomOverSampler
from imblearn.pipeline import Pipeline

In [233]:
ros_25 = RandomOverSampler(
    sampling_strategy=0.25,
    random_state=42
)

In [234]:
knn_ros25_pipeline = Pipeline([
    ('ct', ct),
    ('oversampler', ros_25),
    ('classifier', KNeighborsClassifier())
])
param_grid_ros25 = {
    'classifier__n_neighbors' : [1, 3, 5, 7, 9, 11],
    #'classifier__weights' : ['uniform', 'distance']
}
f1_yes = make_scorer(
    f1_score,
    pos_label = 'yes'
)

In [235]:
grid_search = GridSearchCV(
    estimator=knn_ros25_pipeline,
    param_grid=param_grid_ros25,
    scoring=f1_yes,
    cv=5,
    n_jobs=-1
)
grid_search.fit(x_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('ct',
                                        ColumnTransformer(transformers=[('numerical',
                                                                         StandardScaler(),
                                                                         ['age',
                                                                          'balance',
                                                                          'campaign',
                                                                          'previous',
                                                                          'day',
                                                                          'was_previously_contacted',
                                                                          'days_since_prev_contact',
                                                                          'month_sin',
                                                                          'month_cos']),
                                                                        ('categorical',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['job',
                                                                          'marital',
                                                                          'default',
                                                                          'housing',
                                                                          'loan',
                                                                          'contact',
                                                                          'poutcome',
                                                                          'education'])])),
                                       ('oversampler',
                                        RandomOverSampler(random_state=42,
                                                          sampling_strategy=0.25)),
                                       ('classifier', KNeighborsClassifier())]),
             n_jobs=-1,
             param_grid={'classifier__n_neighbors': [1, 3, 5, 7, 9, 11]},
             scoring=make_scorer(f1_score, response_method='predict', pos_label=yes))

In [236]:
print('best k: ', grid_search.best_params_)
print('best f1 yes score: ', grid_search.best_score_)

best k:  {'classifier__n_neighbors': 11}
best f1 yes score:  0.371408414910286

In [237]:
best_knn_model = grid_search.best_estimator_
y_test_pred = best_knn_model.predict(x_test)

In [238]:
print("Accuracy:", accuracy_score(y_test, y_test_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_test_pred))

Accuracy: 0.8781377861329205

Confusion Matrix:
[[7578  407]
 [ 695  363]]

Classification Report:
              precision    recall  f1-score   support

          no       0.92      0.95      0.93      7985
         yes       0.47      0.34      0.40      1058

    accuracy                           0.88      9043
   macro avg       0.69      0.65      0.66      9043
weighted avg       0.86      0.88      0.87      9043

In [239]:
results = pd.DataFrame(grid_search.cv_results_)

results[
    [
        "param_classifier__n_neighbors",
        #"param_classifier__weights",
        "mean_test_score",
        "rank_test_score"
    ]
].sort_values("rank_test_score")

   param_classifier__n_neighbors  mean_test_score  rank_test_score
5                             11         0.371408                1
4                              9         0.364578                2
3                              7         0.351508                3
2                              5         0.332529                4
1                              3         0.319152                5
0                              1         0.289060                6

In [242]:
best_knn_model.fit(x_train, y_train)
print(best_knn_model)

Pipeline(steps=[('ct',
                 ColumnTransformer(transformers=[('numerical', StandardScaler(),
                                                  ['age', 'balance', 'campaign',
                                                   'previous', 'day',
                                                   'was_previously_contacted',
                                                   'days_since_prev_contact',
                                                   'month_sin', 'month_cos']),
                                                 ('categorical',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['job', 'marital', 'default',
                                                   'housing', 'loan', 'contact',
                                                   'poutcome',
                                                   'education'])])),
                ('oversampler',
                 RandomOverSampler(random_state=42, sampling_strategy=0.25)),
                ('classifier', KNeighborsClassifier(n_neighbors=11))])

In [245]:
import joblib
joblib.dump(
    best_knn_model,
    "bank_marketing_model.joblib"
)

['bank_marketing_model.joblib']